version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm start
  
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - PORT=5000
    depends_on:
      - client
